name: Build

on:
  - push
  - pull_request
  - workflow_call  # allow us to use this workflow in other workflows

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        PYTHON_VERSION: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - run: pip install poetry
      - uses: actions/setup-python@v4
        with:
          cache: 'poetry'
          python-version: ${{ matrix.PYTHON_VERSION }}
      - run: poetry install -vvv
      - run: poetry run python -m unittest discover -vb tests
      - run: poetry build -vvv --no-interaction
