name: Deploy

# Adapted from:
#   https://stackoverflow.com/a/71489231

on:
  push:
    tags: [ '**' ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - run: pip install poetry
      - uses: actions/setup-python@v4
        with:
          cache: 'poetry'
          python-version: '3.10'
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
